const BAD_REQUEST_ERROR_CODE = 400;
const NOT_FOUND_ERROR_CODE = 404;
const INTERNAL_SERVER_ERROR_CODE = 500;
const CREATED_SUCCESS_CODE = 201;
const OK_SUCCESS_CODE = 200;

module.exports = {
  BAD_REQUEST_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  INTERNAL_SERVER_ERROR_CODE,
  CREATED_SUCCESS_CODE,
  OK_SUCCESS_CODE,
};
