const BAD_REQUEST_ERROR_CODE = 400;
const UNAUTHORIZED__ERROR_CODE = 401;
const NOT_FOUND_ERROR_CODE = 404;
const INTERNAL_SERVER_ERROR_CODE = 500;
const FORBIDDEN_ERROR_CODE = 403;

module.exports = {
  BAD_REQUEST_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  INTERNAL_SERVER_ERROR_CODE,
  UNAUTHORIZED__ERROR_CODE,
  FORBIDDEN_ERROR_CODE,
};
